#server:
#  port: 443
#  ssl:
#    key-store: classpath:ssl/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: 1234
server:
  port: 0
spring:
  application:
    name: web-flux-service
  profiles:
    include: mongodb, swagger, rsocket, eureka
